version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: deployments/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wuser
      WORDPRESS_DB_PASSWORD: wpassword
      WORDPRESS_DB_NAME: wdb
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wdb
      MYSQL_USER: wuser
      MYSQL_PASSWORD: wpassword
      MYSQL_ROOT_PASSWORD: wpassword

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - wordpress
